services:
  - type: web
    name: n8n-render-ffmeg
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: aws-0-eu-central-1.pooler.supabase.com
      - key: DB_POSTGRESDB_PORT
        value: "6543"
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres.fpaspkrlwethghmzxdrn
      - key: DB_POSTGRESDB_PASSWORD
        value: 123!@qweQASD
      - key: DB_POSTGRESDB_SCHEMA
        value: public
      - key: DB_POSTGRESDB_SSL
        value: "true"
      - key: DB_POSTGRESDB_POOL_SIZE
        value: "2"
      - key: DB_POSTGRESDB_ACQUIRE_CONNECTION_TIMEOUT
        value: "60000"
      - key: N8N_PORT
        value: 10000
      - key: N8N_HOST
        value: n8n-render-ffmeg.onrender.com
      - key: WEBHOOK_URL
        value: https://n8n-render-ffmeg.onrender.com
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-render-ffmeg.onrender.com
      - key: N8N_ENCRYPTION_KEY
        value: ZYwTyoHyL4K5iKqvQfNZq2nNNRYK0IqmRUUaxbZ
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_TRUST_PROXY
        value: "true"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "false"
      - key: N8N_LOG_LEVEL
        value: info
      - key: NODE_ENV
        value: production
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
